### ISSUE TITLE
OdometryHelper when odom not yet available

### ISSUE THREAD

**Issue by AlexReimann** [yujinrobot/yujin_ocs#110]
The OdometryHelper currently [gives](https://github.com/yujinrobot/yujin_ocs/blob/kinetic/yocs_navi_toolkit/src/lib/odometry_helper.cpp#L38) a non normalized quaternion as orientation when the odometry is requested when no odometry has been published yet.
This is because the [odometry_ variable](https://github.com/yujinrobot/yujin_ocs/blob/kinetic/yocs_navi_toolkit/include/yocs_navi_toolkit/odometry_helper.hpp#L71) [is initialized with the default](https://github.com/yujinrobot/yujin_ocs/blob/kinetic/yocs_navi_toolkit/src/lib/odometry_helper.cpp#L21) which is [0 0 0 0].
This leads to some problems and maybe nans when it is used in the code.

So should properly initialize it or throw an error etc. 
There is actually not a really a reasonable default initialization for that variable (but a normalized quaternion is better than getting some nans).

**Comment by AlexReimann** [comment]
fyi @bit-pirate

**Comment by AlexReimann** [comment]
Updated the description.

The problem mainly is that our trajectory controller uses the current odom and the past issued commands to estimate where the robot will be in the future.
This estimate is then passed to the local planner which leads to the local planner running into problems because the pose is faulty (a non-normalized quaternion as orientation)

**Comment by AlexReimann** [comment]
I'll catch this for now by checking for a non-normalized quaternion.
Maybe this is the actual intent behind the default quaternion constructor leading to an invalid quaternion (or rather not normalized).
Maybe close this..?

**Comment by stonier** [comment]
Sending out a non-normalised quaternion and then requiring a user to _interpret_ that as uninitialised would be quite bad design. There are much easier ways to help a user understand its uninitialised than that.

Initialising it as well with `[0 0 0 1]` would also be quite bad design. There are valid use cases where the user would need to know if it's initialised or not, and that is not enough information for those cases.

I'd say the cleanest solution is to have the odometry in a std shared pointer which only gets initialised after it's got data (user can check the shared pointer himself) and then move the position/velocity processing methods to library functions. Separate data collection and data processing concerns.

Otherwise use exceptions in each method for when it's uninitialised. Or a combination of the shared pointer/exception idea.

Keep in mind that exceptions are usually an expensive option. For control systems I typically only take advantage of their usefulness in constructor or init functions.

**Comment by stonier** [comment]
I don't think there is anything special about these classes - I just pulled them from your clrrt just after you finished your master's period so I could re-use them in various places.

Feel free to take ownership of what is in this package.

**Comment by AlexReimann** [comment]
Ohh, so it's my shitty code. I see..

**Comment by AlexReimann** [comment]
Fixed with pr #119
