### ISSUE TITLE
Use odom or odom_combined?

### ISSUE THREAD

**Issue by stonier** [yujinrobot/yujin_ocs#7]
I wonder if we should move this from odom (nav_msgs/Odometry) to odom_combined (geometry_msgs/PoseWithCovarianceStamped).

Point being, ros by convention typically looks to the latter as output from the [robot_pose_ekf](http://ros.org/wiki/robot_pose_ekf), not the raw odometry.

**Comment by stonier** [comment]
If we'd like to use both - perhaps parameterise it to use one or the other.

**Comment by corot** [comment]
I think odom_combined  is mostly provided for debug, as typically we use tf for robot pose, and odom for velocities, but odom_combined just provides pose

**Comment by stonier** [comment]
Velocities is the key point for the velocity smoother - I'd forgotten the odom combined doesn't post velocities.

If we properly separate odom and imu_data, then we probably need a twist_combined for the velocity smoother. Currently it's not essential for the kobuki since we use the gyro by default for the heading (position and rate) but that is pretty inflexible as a general rule. turtlebot_create is a good example where that is not possible/done.

**Comment by corot** [comment]
Let's revive this issue. I also added a trello card pointing to here. I was talking with Einstein about this, and we realized that we are using TurtleBot 1 configuration just as legacy, but it doesn't fit well to TurtleBot 2, I think.

**Current situation** (correct me if I'm wrong, or tell me if it's not clear enough)
- kobuki_node publishes odom (pose and speed from encoders) and imu_data (heading and angular speed from gyro)
- robot_pose_ekf subscribes to both, and uses an EKF to fuse and filter
- robot_pose_ekf publishes odom_combined (only pose) and tf
- navi stack uses this tf for pose and odom (only encoders) for speed; odom_combined is ignored
- as imu_data covariance is much lower than odom one, it dominates orientation. Encoders orientation is overshadowed, but angular speed is entirely based on them

**Is this good?**
- robot_pose_ekf is a node, so it adds extra latency on tf publishing
- angular speed and heading are based on different sensors
- we are not doing real sensor fusion, as imu entirely overshadows encoders
- we are not managing weak points of our sensors, namely imu not reporting very low rotation rates
- BUT I suppose TurtleBot 1 did this way for a _good_ reason. I think it is because on Create the gyro was an extra, so this was a crappy way to use it without modifying the create_node. In our case, this can only happen if the gyro breaks...

**Alternative?**
- Discard robot_pose_ekf and fuse encoders and imu inside kobuki_node, taking advantage of our strong points and dealing with the weak ones

**Comment by stonier** [comment]
When ros pose ekf publishes the tf, does it publish it with the 'now' timestamp, not the sensor timestamps?

**Comment by corot** [comment]
nop, is smarter than this:  stamps with the older fussed odometry message. That's why I didn't mention time in my depiction

**Comment by stonier** [comment]
Let's try discarding the robot pose ekf in a branch once we've got the rest of hydro basically working. Reason being: It's currently redundant since gyro and odometry are in the same process and this creates an extra load.

If somone wants to re-insert it to fuse some esoteric sensor then they can easily add the robot_pose_ekf themselves or they can bugfix and we can re-release.

If they want to play around with covariances, then they have to play with the kobuki sources anyway.

**Comment by corot** [comment]
Done:
- https://github.com/yujinrobot/kobuki/commit/9c4835ad5b2eb3a4945f57076501b7699057ec66
- https://github.com/turtlebot/turtlebot/commit/24572cb8fcc2c9d3b16ff8cf39c4a83558126ac8
- https://github.com/turtlebot/turtlebot_simulator/commit/ea95fc0dca9fcc739ec04e790b1fe2f29bffc726

I added parameter use_imu_heading on kobuki_node, so it gets trivial to switch back to use robot_pose_ekf.

I just overwrite encoders heading with imu heading, but now we have the option of more intelligent combinations... for example avoid imu when describing very wide arcs, as @jakan2 says it is not reliable on these cases.
